name: meditation_app_native
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon_logo.svg
    - assets/images/person_med.svg

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Thin.ttf
          weight: 100
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-Black.ttf
          weight: 900

flutter_launcher_icons:
  image_path: "assets/icons/meditation_app_icon.png"
  android: true
  ios: true
